CREATE DATABASE PROJETO_INTEGRADO_HML;

USE PROJETO_INTEGRADO_HML;

CREATE TABLE CLIENTE(
	id int(11) NOT NULL auto_increment,
	NOME_EMPRESA VARCHAR (50)NOT NULL ,
	CNPJ VARCHAR (15) NOT NULL,
	TELEFONE VARCHAR (15) NOT NULL,
	LOGRADOURO VARCHAR (100) NOT NULL,
	COMPLEMENTO VARCHAR (50) NOT NULL,
	CIDADE VARCHAR (30) NOT NULL,
	UF CHAR(2) NOT NULL,
	PRIMARY KEY  (id)

)
;